feat(euiccinfo): add euiccCiPKIdListFor{Verification,Signing}
estkme-group/lpac pull request #29
Opened 2023-12-30 15:03 UTC by CoelacanthusHex

According to RFC3280 section 4.2.1.2, SubjectKeyIdentifier is byte array of SHA-1 or subset of SHA-1, so we print it as HEX string, just as InfiLPA does.

Ref: https://datatracker.ietf.org/doc/html/rfc3280#section-4.2.1.2

2023-12-30 15:04 UTC, septs approved these changes

2024-01-01 11:45 UTC, estkme requested changes

2024-01-01 11:45 UTC, estkme commented on src/applet/chip/info.c
> +    struct es10cex_euiccinfo2 *euiccinfo2 = NULL;
这里可能不太对

2024-01-01 11:45 UTC, estkme commented on src/applet/chip/info.c
> +    if (es10cex_get_euiccinfo2(&euicc_ctx, euiccinfo2) == 0)
这里可能不太对

2024-01-01 11:49 UTC, estkme requested changes

2024-01-01 11:49 UTC, estkme commented on euicc/es10cex.h
> +        int count;
这个count其实是不必须的，可以使用NULL-Terminate array list，即最后一个指针指向NULL，这也符合整个项目的风格（HTTP Interface中对header的数据结构）

2024-01-01 12:32 UTC, CoelacanthusHex commented on src/applet/chip/info.c
> +    struct es10cex_euiccinfo2 *euiccinfo2 = NULL;
done by alloc an object for it, see [`b1f20ad` (#29)](https://github.com/estkme-group/lpac/pull/29/commits/b1f20adfeeaba5ad813fe33bcf2958eabe90c41e)

2024-01-01 12:32 UTC, CoelacanthusHex commented on euicc/es10cex.h
> +        int count;
Done in [`1048f03` (#29)](https://github.com/estkme-group/lpac/pull/29/commits/1048f03350c131e68a282fbbce1f78e73383a398)

2024-01-04 02:38 UTC, merged